### ISSUE TITLE
404 - page not found - On clicking the link

### ISSUE THREAD

**Issue by geojoseph** [SoftwareEngineeringEcosystem/Blog#2]
@KlausHaeuptleSAP  Thanks for the nice writing. Much appreciated. !!
There is a small bug in the article setup. The link for [SAPUI5 Template Checklist for Onboarding new SAPUI5 software engineers](https://github.com/SoftwareEngineeringEcosystem/Blog/blob/main/ISSUE_TEMPLATE/sapui5-developer-onboarding-for-agile-software-engineering.md) in the primary article seems to be broken.
<img width="555" alt="image" src="https://github.com/SoftwareEngineeringEcosystem/Blog/assets/17277085/389f1dda-3db8-4284-abb6-47c414a4956f">

<img width="636" alt="image" src="https://github.com/SoftwareEngineeringEcosystem/Blog/assets/17277085/0ff54b42-a95a-4403-9811-0969728bfb8b">

**Comment by KlausHaeuptleSAP** [comment]
@geojoseph: Thanks for the feedback! Is now corrected
